# Generated by Django 2.0.6 on 2018-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=150)),
                ('Person_id', models.AutoField(primary_key=True, serialize=False)),
                ('Person_contact_No', models.CharField(max_length=10)),
                ('Address_person', models.CharField(max_length=150)),
            ],
        ),
    ]
