# Generated by Django 2.0.6 on 2018-06-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address_person',
            new_name='Person_address',
        ),
    ]
